"""
repositories/field_repository.py — Field CRUD
===============================================

Handles database operations for Field records — the second level of the
Farm → Field → SimulationRun hierarchy.

Design notes:
  - Fields are spatial entities: latitude/longitude are required for all
    create operations.  The ix_fields_lat_lon index makes coordinate-based
    lookups efficient.
  - get_all_fields() supports filtering by farm_id and optional bounding box
    (lat/lon range) to support future "show all fields near this coordinate"
    features without requiring PostGIS.
  - delete_field() cascades to SimulationRuns and DailyOutputs via the DB-
    level ON DELETE CASCADE and the Python-level cascade="all, delete-orphan"
    on Field.simulation_runs.

Session lifecycle:
    Same contract as SimulationRepository — no commit/rollback here.

Methods:
    create_field(field)              → Field
    get_field(field_id)              → Field | None
    get_all_fields(...)              → list[Field]
    delete_field(field_id)           → bool

FastAPI dependency:
    def get_field_repo(db: Session = Depends(get_db)) -> FieldRepository:
        return FieldRepository(db)
"""

import uuid
import logging
from typing import Optional

from sqlalchemy import select, and_
from sqlalchemy.orm import Session

from backend.app.models.field import Field

logger = logging.getLogger(__name__)


class FieldRepository:
    """Data access layer for Field records.

    Args:
        db: An open SQLAlchemy Session (injected by FastAPI Depends(get_db)).
    """

    def __init__(self, db: Session) -> None:
        self.db = db

    # ── Write operations ──────────────────────────────────────────────────

    def create_field(self, field: Field) -> Field:
        """Persist a new Field to the database.

        Accepts a fully constructed Field ORM instance.  If `field.id` is not
        set, a UUID is generated by SQLAlchemy on flush.

        Args:
            field: A Field instance in transient (not yet added) state.
                   Required fields: farm_id, name, latitude, longitude.

        Returns:
            The same Field instance after flush and refresh.
            server_default columns (created_at, updated_at) are populated.

        Raises:
            sqlalchemy.exc.IntegrityError: If farm_id references a non-existent
                Farm (FK violation).  Propagated to the caller for handling.

        Example:
            field = Field(
                id=uuid.uuid4(),
                farm_id=farm.id,
                name="Block A — Kharif 2020",
                latitude=26.8,
                longitude=80.9,
                area_ha=4.5,
            )
            saved = repo.create_field(field)
            print(saved.created_at)
        """
        self.db.add(field)
        self.db.flush()
        self.db.refresh(field)
        logger.info(
            "Created Field id=%s name=%r lat=%.4f lon=%.4f farm_id=%s",
            field.id, field.name, field.latitude, field.longitude, field.farm_id,
        )
        return field

    def delete_field(self, field_id: uuid.UUID) -> bool:
        """Delete a Field and cascade-delete all its SimulationRuns and DailyOutputs.

        The cascade is enforced at two levels:
          1. Python (ORM): cascade="all, delete-orphan" on Field.simulation_runs
             handles tracked ORM objects within the same session.
          2. DB (SQL): ON DELETE CASCADE on simulation_runs.field_id and
             daily_outputs.simulation_run_id handles raw SQL deletes and
             ensures referential integrity even without ORM involvement.

        Args:
            field_id: UUID of the Field to delete.

        Returns:
            True if the field was found and deleted.
            False if no field with that ID exists.
        """
        field = self.db.get(Field, field_id)
        if field is None:
            logger.warning("delete_field: id=%s not found", field_id)
            return False

        self.db.delete(field)
        self.db.flush()
        logger.info(
            "Deleted Field id=%s name=%r (cascade → SimulationRuns → DailyOutputs)",
            field_id, field.name,
        )
        return True

    # ── Read operations ───────────────────────────────────────────────────

    def get_field(self, field_id: uuid.UUID) -> Optional[Field]:
        """Fetch a single Field by its UUID primary key.

        Uses Session.get() to check the identity map first (zero DB hit
        when the field was already loaded in the same request).

        Args:
            field_id: UUID primary key of the Field.

        Returns:
            The Field instance, or None if not found.
        """
        field = self.db.get(Field, field_id)
        if field is None:
            logger.debug("get_field: id=%s not found", field_id)
        return field

    def get_all_fields(
        self,
        *,
        farm_id: Optional[uuid.UUID] = None,
        lat_min: Optional[float] = None,
        lat_max: Optional[float] = None,
        lon_min: Optional[float] = None,
        lon_max: Optional[float] = None,
        limit: int = 200,
        offset: int = 0,
    ) -> list[Field]:
        """Fetch Field records with optional farm and spatial filtering.

        The ix_fields_lat_lon composite index accelerates bounding-box queries.
        The ix_fields_farm_id index accelerates farm_id filtering.

        Args:
            farm_id:  Filter by parent Farm UUID.  Returns all farms' fields
                      if None.
            lat_min:  Minimum latitude (inclusive) for bounding-box filter.
            lat_max:  Maximum latitude (inclusive) for bounding-box filter.
            lon_min:  Minimum longitude (inclusive) for bounding-box filter.
            lon_max:  Maximum longitude (inclusive) for bounding-box filter.
            limit:    Maximum records to return (default 200).
            offset:   Records to skip for pagination (default 0).

        Returns:
            List of Field instances ordered by name ASC.
            Empty list if no fields match the filter criteria.

        Example — all fields in a farm:
            repo.get_all_fields(farm_id=farm.id)

        Example — all fields in a geographic bounding box (e.g. Lucknow district):
            repo.get_all_fields(lat_min=26.5, lat_max=27.1, lon_min=80.5, lon_max=81.3)

        Example — paginated global list:
            repo.get_all_fields(limit=50, offset=100)
        """
        stmt = select(Field)

        filters = []
        if farm_id is not None:
            filters.append(Field.farm_id == farm_id)
        if lat_min is not None:
            filters.append(Field.latitude >= lat_min)
        if lat_max is not None:
            filters.append(Field.latitude <= lat_max)
        if lon_min is not None:
            filters.append(Field.longitude >= lon_min)
        if lon_max is not None:
            filters.append(Field.longitude <= lon_max)

        if filters:
            stmt = stmt.where(and_(*filters))

        stmt = stmt.order_by(Field.name.asc()).offset(offset).limit(limit)

        results = self.db.execute(stmt).scalars().all()
        logger.debug(
            "get_all_fields: returned %d records (farm_id=%s, offset=%d, limit=%d)",
            len(results), farm_id, offset, limit,
        )
        return list(results)
