"""
models/simulation_run.py — SimulationRun ORM Model
====================================================

A SimulationRun records one complete WOFOST simulation execution.  It stores:

  1. The INPUT parameters that drove the simulation (crop, dates, flags, etc.)
  2. The SCALAR RESULTS aggregated from the full daily time series (yield, LAI, HI)
  3. The PHENOLOGICAL DATES (emergence, anthesis, maturity)
  4. JSON BLOBS for the full request payload, metrics summary, and optional
     weather/soil snapshots that were used — enabling perfect reproducibility
     and debugging without re-running the simulation.

run_type vocabulary (open-ended string, not an Enum, to remain extensible):
    "baseline"        — rainfed, no irrigation, no assimilation
    "irrigated"       — user-specified irrigation schedule
    "enkf"            — run was part of an EnKF ensemble (Phase 3)
    "whatif"          — counterfactual / scenario run
    "satellite_driven" — corrected by satellite LAI observations (Phase 4)

Denormalised lat/lon columns:
    Even though Field already carries lat/lon, they are stored again here
    because the user might submit coordinates that differ from the field
    centroid (e.g. a corner coordinate, or a simulated sub-plot).
    Denormalization enables fast filtering without a JOIN to fields.

JSON columns:
    SQLite: stored as plain TEXT (SQLAlchemy serialises via json module).
    PostgreSQL: stored as JSONB (binary JSON, supports GIN indexing).
    Alembic's PostgreSQL dialect auto-upgrades JSON→JSONB in migrations.

Relationships:
    SimulationRun.field        → Field (many-to-one, FK field_id)
    SimulationRun.daily_outputs → DailyOutput (one-to-many, cascade delete)
"""

import datetime
import uuid
from typing import TYPE_CHECKING, Any

from sqlalchemy import (
    Boolean, Date, Float, ForeignKey,
    Index, Integer, JSON, String, Text,
)
from sqlalchemy.orm import Mapped, mapped_column, relationship
from sqlalchemy.types import Uuid

from backend.app.db.base import Base, TimestampMixin

if TYPE_CHECKING:
    from backend.app.models.field import Field
    from backend.app.models.daily_output import DailyOutput


class SimulationRun(TimestampMixin, Base):
    """One complete WOFOST simulation execution stored for a Field.

    Immutable after status becomes 'completed' or 'failed'.
    The daily time series is in the related DailyOutput records.

    Table: simulation_runs
    """

    __tablename__ = "simulation_runs"

    # ── Indexes ───────────────────────────────────────────────────────────
    __table_args__ = (
        # Most common query: "all runs for a field, ordered by sowing_date"
        Index("ix_simrun_field_sowing", "field_id", "sowing_date"),
        # Crop-type filtering: "all wheat runs globally"
        Index("ix_simrun_crop_variety", "crop", "variety"),
        # Spatial filtering by denormalised coordinates
        Index("ix_simrun_lat_lon", "latitude", "longitude"),
        # Status monitoring
        Index("ix_simrun_status", "status"),
    )

    # ── Primary key ───────────────────────────────────────────────────────
    id: Mapped[uuid.UUID] = mapped_column(
        Uuid(as_uuid=True),
        primary_key=True,
        default=uuid.uuid4,
        doc=(
            "UUID primary key.  Generated by the application before DB insert "
            "so the caller knows the run ID without a round-trip."
        ),
    )

    # ── Foreign key ───────────────────────────────────────────────────────
    field_id: Mapped[uuid.UUID | None] = mapped_column(
        Uuid(as_uuid=True),
        ForeignKey("fields.id", ondelete="CASCADE"),
        nullable=True,       # nullable=True allows simulations run without a saved Field
        index=True,
        doc=(
            "FK → fields.id.  NULL is allowed for ad-hoc simulations "
            "submitted via the API without a pre-registered field. "
            "Set to the field's UUID when the run is attached to a farm's field."
        ),
    )

    # ── Run classification ────────────────────────────────────────────────
    run_type: Mapped[str] = mapped_column(
        String(64),
        nullable=False,
        default="baseline",
        doc=(
            "Category of this simulation run.  Open-ended string (not an Enum) "
            "for extensibility. Recommended values: "
            "'baseline' (rainfed), 'irrigated', 'enkf', 'whatif', 'satellite_driven'."
        ),
    )

    status: Mapped[str] = mapped_column(
        String(32),
        nullable=False,
        default="completed",
        doc=(
            "Lifecycle state of the run. "
            "'queued': accepted but not yet started (async mode). "
            "'running': simulation in progress. "
            "'completed': finished successfully, results available. "
            "'failed': engine threw an exception — see error_message."
        ),
    )

    error_message: Mapped[str | None] = mapped_column(
        Text,
        nullable=True,
        doc=(
            "If status='failed', stores the exception message and type "
            "for debugging.  NULL when status='completed'."
        ),
    )

    # ── Model identity ────────────────────────────────────────────────────
    model_name: Mapped[str] = mapped_column(
        String(128),
        nullable=False,
        default="Wofost72_WLP_FD",
        doc=(
            "PCSE engine class name used for this run "
            "(e.g. 'Wofost72_WLP_FD', 'Wofost72_PP'). "
            "Stored for reproducibility — engine class determines water balance behaviour."
        ),
    )

    model_version: Mapped[str] = mapped_column(
        String(64),
        nullable=False,
        default="7.2",
        doc=(
            "WOFOST model version string (e.g. '7.2'). "
            "Allows filtering runs by model generation in cross-version comparisons."
        ),
    )

    # ── Spatial inputs (denormalised for fast filtering) ──────────────────
    latitude: Mapped[float] = mapped_column(
        Float,
        nullable=False,
        doc=(
            "Decimal-degree latitude (WGS84) passed to the simulation. "
            "May differ from Field.latitude if the user overrode coordinates."
        ),
    )

    longitude: Mapped[float] = mapped_column(
        Float,
        nullable=False,
        doc=(
            "Decimal-degree longitude (WGS84) passed to the simulation. "
            "May differ from Field.longitude if the user overrode coordinates."
        ),
    )

    # ── Crop configuration ────────────────────────────────────────────────
    crop: Mapped[str] = mapped_column(
        String(64),
        nullable=False,
        doc="Lowercase PCSE crop name (e.g. 'wheat', 'rice', 'maize'). "
            "Must match a key in the WOFOST_crop_parameters YAML database.",
    )

    variety: Mapped[str] = mapped_column(
        String(128),
        nullable=False,
        doc="PCSE variety identifier within the crop's YAML file "
            "(e.g. 'apache', 'Rice_IR64', 'Winter_wheat_101').",
    )

    # ── Season dates ──────────────────────────────────────────────────────
    sowing_date: Mapped[datetime.date] = mapped_column(
        Date,
        nullable=False,
        doc="Sowing (or transplanting) date for this simulation season (ISO date).",
    )

    harvest_date: Mapped[datetime.date | None] = mapped_column(
        Date,
        nullable=True,
        doc=(
            "Expected harvest date used as the simulation end date. "
            "NULL if no harvest date was specified (simulation ran until maturity)."
        ),
    )

    # ── Data source flags ─────────────────────────────────────────────────
    use_real_weather: Mapped[bool] = mapped_column(
        Boolean,
        nullable=False,
        default=True,
        doc=(
            "True if the run used real NASA POWER weather data; "
            "False if synthetic (deterministic test) weather was used."
        ),
    )

    use_real_soil: Mapped[bool] = mapped_column(
        Boolean,
        nullable=False,
        default=True,
        doc=(
            "True if real SoilGrids v2.0 soil hydraulic properties were used; "
            "False if default medium-loam parameters were applied."
        ),
    )

    # ── Scalar results ────────────────────────────────────────────────────
    yield_kg_ha: Mapped[float | None] = mapped_column(
        Float,
        nullable=True,
        doc=(
            "Simulated grain/storage-organ yield [kg dry matter / ha]. "
            "Equivalent to WOFOST TWSO at harvest.  "
            "NULL if the run failed or the crop did not reach maturity."
        ),
    )

    peak_lai: Mapped[float | None] = mapped_column(
        Float,
        nullable=True,
        doc=(
            "Maximum Leaf Area Index reached during the season [m² leaf / m² ground]. "
            "Key indicator of canopy development and satellite-observable quantity."
        ),
    )

    harvest_index: Mapped[float | None] = mapped_column(
        Float,
        nullable=True,
        doc=(
            "Harvest Index = TWSO / TAGP [-]. "
            "Fraction of total above-ground biomass that is harvestable yield. "
            "Typical ranges: wheat 0.40–0.55, rice 0.45–0.55, maize 0.45–0.55."
        ),
    )

    final_tagp: Mapped[float | None] = mapped_column(
        Float,
        nullable=True,
        doc=(
            "Total Above-Ground Production at season end [kg dry matter / ha]. "
            "Sum of leaf + stem + storage organ biomass. "
            "Monotonically increases through the season."
        ),
    )

    final_twso: Mapped[float | None] = mapped_column(
        Float,
        nullable=True,
        doc=(
            "Total Weight of Storage Organs at season end [kg / ha]. "
            "Same value as yield_kg_ha, stored separately for clarity "
            "and to match WOFOST variable naming."
        ),
    )

    total_days: Mapped[int | None] = mapped_column(
        Integer,
        nullable=True,
        doc=(
            "Number of daily timesteps executed by the simulation engine. "
            "Includes the 14-day pre-sowing campaign buffer."
        ),
    )

    # ── Phenological event dates (from WOFOST get_summary_output) ─────────
    dos: Mapped[datetime.date | None] = mapped_column(
        Date,
        nullable=True,
        doc="Date of Sowing (DOS) — first simulation day with DVS > -0.1.",
    )

    doe: Mapped[datetime.date | None] = mapped_column(
        Date,
        nullable=True,
        doc="Date of Emergence (DOE) — DVS transitions from 'emerging' to 'vegetative'.",
    )

    doa: Mapped[datetime.date | None] = mapped_column(
        Date,
        nullable=True,
        doc="Date of Anthesis / Flowering (DOA) — DVS = 1.0.",
    )

    dom: Mapped[datetime.date | None] = mapped_column(
        Date,
        nullable=True,
        doc="Date of Maturity (DOM) — DVS = 2.0. NULL if crop was harvested early.",
    )

    doh: Mapped[datetime.date | None] = mapped_column(
        Date,
        nullable=True,
        doc="Date of Harvest (DOH) — the harvest date actually reached by the engine.",
    )

    # ── JSON payloads ─────────────────────────────────────────────────────
    request_payload: Mapped[dict[str, Any] | None] = mapped_column(
        JSON,
        nullable=True,
        doc=(
            "Full SimulateRequest body as a JSON object. "
            "Enables exact reproduction of the run: re-submit this payload "
            "to get the same simulation result."
        ),
    )

    metrics_payload: Mapped[dict[str, Any] | None] = mapped_column(
        JSON,
        nullable=True,
        doc=(
            "AgronomicMetrics response dict as JSON "
            "(total_days, peak_lai, final_dvs, final_tagp_kg_ha, "
            "final_twso_kg_ha, harvest_index). "
            "Redundant with the scalar columns above but preserves the full "
            "API response for audit and debugging."
        ),
    )

    summary_payload: Mapped[dict[str, Any] | None] = mapped_column(
        JSON,
        nullable=True,
        doc=(
            "PhenologicalSummary response dict as JSON "
            "(dos, doe, doa, dom, doh, laimax, tagp, twso). "
            "Redundant with scalar columns but stored for full response replay."
        ),
    )

    weather_snapshot: Mapped[dict[str, Any] | None] = mapped_column(
        JSON,
        nullable=True,
        doc=(
            "Summary of the weather data used for this run. "
            "Recommended keys: source ('nasa_power'|'synthetic'), "
            "first_date, last_date, latitude, longitude, "
            "tmax_mean_Cgrain_fill, tmin_mean_C_grain_fill. "
            "Not the full daily series (that is in DailyOutput). "
            "Useful for diagnosing climate-related anomalies (heat stress, drought)."
        ),
    )

    soil_snapshot: Mapped[dict[str, Any] | None] = mapped_column(
        JSON,
        nullable=True,
        doc=(
            "The soil parameters (SMW, SMFCF, SM0, CRAIRC, RDMSOL, K0, SOPE, KSUB) "
            "exactly as passed to the WOFOST engine. "
            "Source is either SoilGrids v2.0 or the default medium-loam fallback."
        ),
    )

    warnings: Mapped[list[str] | None] = mapped_column(
        JSON,
        nullable=True,
        doc=(
            "List of warning strings emitted during the simulation. "
            "Examples: 'SMFCF adjusted upward (SoilGrids ordering violation)', "
            "'crop terminated by max_duration before maturity'. "
            "Empty list [] means the simulation ran without any warnings."
        ),
    )

    notes: Mapped[str | None] = mapped_column(
        Text,
        nullable=True,
        doc=(
            "Free-text notes added by the API caller or an agronomist "
            "(e.g. 'Test run for paper Table 3', 'Validated against CRIDA data 2020')."
        ),
    )

    # ── Relationships ──────────────────────────────────────────────────────
    field: Mapped["Field | None"] = relationship(
        "Field",
        back_populates="simulation_runs",
        doc="Parent Field this run belongs to. NULL for ad-hoc (unattached) runs.",
    )

    daily_outputs: Mapped[list["DailyOutput"]] = relationship(
        "DailyOutput",
        back_populates="simulation_run",
        # CASCADE: deleting a SimulationRun purges all its DailyOutput rows.
        cascade="all, delete-orphan",
        # Lazy loading is fine here; daily_outputs are large and should only
        # be fetched when explicitly requested (e.g. GET /runs/{id}/daily).
        lazy="select",
        doc=(
            "Ordered list of daily simulation states for this run. "
            "One DailyOutput row per simulated day.  "
            "A 365-day simulation produces ~379 rows (including 14-day buffer)."
        ),
    )

    def __repr__(self) -> str:
        return (
            f"<SimulationRun id={self.id!s:.8} crop={self.crop!r} "
            f"variety={self.variety!r} sowing={self.sowing_date} "
            f"yield={self.yield_kg_ha} status={self.status!r}>"
        )
