"""add_raw_weather_records_table_v3

Revision ID: 1c249fc498aa
Revises: f16eb05e3297
Create Date: 2026-06-22 19:33:34.523024

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import Text
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "1c249fc498aa"
down_revision: Union[str, Sequence[str], None] = "f16eb05e3297"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "raw_weather_records",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "field_id",
            sa.UUID(),
            nullable=False,
            comment="Foreign key referencing the specific agricultural field",
        ),
        sa.Column(
            "date",
            sa.Date(),
            nullable=False,
            comment="The specific calendar date for this weather snapshot",
        ),
        sa.Column("latitude", sa.Float(), nullable=False),
        sa.Column("longitude", sa.Float(), nullable=False),
        sa.Column(
            "source",
            sa.String(length=50),
            nullable=False,
            comment="API Source identifier",
        ),
        sa.Column(
            "api_status",
            sa.String(length=20),
            nullable=False,
            comment="Ingestion quality tracking status: 'success', 'partial', or 'failed'",
        ),
        sa.Column(
            "temperature_2m", sa.Float(), nullable=True, comment="Mean temperature [°C]"
        ),
        sa.Column(
            "temperature_min", sa.Float(), nullable=True, comment="Min temperature [°C]"
        ),
        sa.Column(
            "temperature_max", sa.Float(), nullable=True, comment="Max temperature [°C]"
        ),
        sa.Column(
            "precipitation", sa.Float(), nullable=True, comment="Precipitation [mm/day]"
        ),
        sa.Column(
            "radiation",
            sa.Float(),
            nullable=True,
            comment="Shortwave radiation [MJ/m²/day]",
        ),
        sa.Column("wind_speed", sa.Float(), nullable=True, comment="Wind speed [m/s]"),
        sa.Column(
            "vapor_pressure",
            sa.Float(),
            nullable=True,
            comment="Calculated vapor pressure [hPa]",
        ),
        sa.Column(
            "toa_radiation",
            sa.Float(),
            nullable=True,
            comment="TOA radiation [MJ/m²/day]",
        ),
        sa.Column(
            "raw_payload",
            sa.JSON(),
            nullable=False,
            comment="Stores full original NASA POWER JSON response dictionary for historical data lineage",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "field_id", "date", name="uq_field_raw_weather_date_snapshot"
        ),
    )
    with op.batch_alter_table("raw_weather_records", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_raw_weather_records_date"), ["date"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_raw_weather_records_field_id"), ["field_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_raw_weather_records_id"), ["id"], unique=False
        )

    op.create_table(
        "scenario_definitions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=256), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "generator_type",
            sa.Enum("SOWING_DATE", "IRRIGATION", "VARIETY", name="generator_type_enum"),
            nullable=False,
        ),
        sa.Column("parameter_name", sa.String(length=128), nullable=False),
        sa.Column("parameter_values", sa.JSON(), nullable=False),
        sa.Column("base_simulation_id", sa.Uuid(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["base_simulation_id"], ["simulation_runs.id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("scenario_definitions", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_scenario_definitions_base_simulation_id"),
            ["base_simulation_id"],
            unique=False,
        )
        batch_op.create_index(
            "ix_scendef_base_sim", ["base_simulation_id"], unique=False
        )
        batch_op.create_index(
            "ix_scendef_generator_type", ["generator_type"], unique=False
        )

    op.create_table(
        "scenario_comparisons",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("scenario_id", sa.Uuid(), nullable=False),
        sa.Column("best_yield_simulation", sa.Uuid(), nullable=True),
        sa.Column("lowest_water_use_simulation", sa.Uuid(), nullable=True),
        sa.Column("lowest_stress_simulation", sa.Uuid(), nullable=True),
        sa.Column("delta_yield_percent", sa.Float(), nullable=True),
        sa.Column("delta_irrigation_mm", sa.Float(), nullable=True),
        sa.Column("delta_stress_days", sa.Integer(), nullable=True),
        sa.Column("ranked_runs", sa.JSON(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["scenario_id"], ["scenario_definitions.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("scenario_id"),
        sa.UniqueConstraint("scenario_id", name="uq_scencomp_scenario"),
    )
    op.create_table(
        "scenario_runs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("scenario_id", sa.Uuid(), nullable=False),
        sa.Column("parameter_value", sa.JSON(), nullable=False),
        sa.Column("simulation_id", sa.Uuid(), nullable=True),
        sa.Column("yield_kg_ha", sa.Float(), nullable=True),
        sa.Column("peak_lai", sa.Float(), nullable=True),
        sa.Column("harvest_index", sa.Float(), nullable=True),
        sa.Column("final_tagp", sa.Float(), nullable=True),
        sa.Column("final_twso", sa.Float(), nullable=True),
        sa.Column("water_stress_days", sa.Integer(), nullable=True),
        sa.Column("total_irrigation_mm", sa.Float(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["scenario_id"], ["scenario_definitions.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["simulation_id"], ["simulation_runs.id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("scenario_runs", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_scenario_runs_scenario_id"), ["scenario_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_scenario_runs_simulation_id"),
            ["simulation_id"],
            unique=False,
        )
        batch_op.create_index("ix_scenrun_scenario_id", ["scenario_id"], unique=False)
        batch_op.create_index(
            "ix_scenrun_simulation_id", ["simulation_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("scenario_runs", schema=None) as batch_op:
        batch_op.drop_index("ix_scenrun_simulation_id")
        batch_op.drop_index("ix_scenrun_scenario_id")
        batch_op.drop_index(batch_op.f("ix_scenario_runs_simulation_id"))
        batch_op.drop_index(batch_op.f("ix_scenario_runs_scenario_id"))

    op.drop_table("scenario_runs")
    op.drop_table("scenario_comparisons")
    with op.batch_alter_table("scenario_definitions", schema=None) as batch_op:
        batch_op.drop_index("ix_scendef_generator_type")
        batch_op.drop_index("ix_scendef_base_sim")
        batch_op.drop_index(batch_op.f("ix_scenario_definitions_base_simulation_id"))

    op.drop_table("scenario_definitions")
    with op.batch_alter_table("raw_weather_records", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_raw_weather_records_id"))
        batch_op.drop_index(batch_op.f("ix_raw_weather_records_field_id"))
        batch_op.drop_index(batch_op.f("ix_raw_weather_records_date"))

    op.drop_table("raw_weather_records")
    # ### end Alembic commands ###
