"""Add assimilation_states table

Revision ID: 29baced2da3c
Revises: 98e23ab1a23e
Create Date: 2026-06-17 15:56:51.321215

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '29baced2da3c'
down_revision: Union[str, Sequence[str], None] = '98e23ab1a23e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assimilation_states',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('field_id', sa.Uuid(), nullable=True),
    sa.Column('simulation_run_id', sa.Uuid(), nullable=True),
    sa.Column('assimilation_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ensemble_mean', sa.JSON(), nullable=False),
    sa.Column('ensemble_covariance', sa.JSON(), nullable=False),
    sa.Column('observation_vector', sa.JSON(), nullable=False),
    sa.Column('innovation_vector', sa.JSON(), nullable=False),
    sa.Column('kalman_gain', sa.JSON(), nullable=False),
    sa.Column('updated_state_vector', sa.JSON(), nullable=False),
    sa.Column('forecast_state_vector', sa.JSON(), nullable=False),
    sa.Column('number_of_members', sa.Integer(), nullable=False),
    sa.Column('observation_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['field_id'], ['fields.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['simulation_run_id'], ['simulation_runs.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('assimilation_states', schema=None) as batch_op:
        batch_op.create_index('ix_assimilation_field_time', ['field_id', 'assimilation_time'], unique=False)
        batch_op.create_index('ix_assimilation_run_time', ['simulation_run_id', 'assimilation_time'], unique=False)
        batch_op.create_index(batch_op.f('ix_assimilation_states_field_id'), ['field_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_assimilation_states_simulation_run_id'), ['simulation_run_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assimilation_states', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_assimilation_states_simulation_run_id'))
        batch_op.drop_index(batch_op.f('ix_assimilation_states_field_id'))
        batch_op.drop_index('ix_assimilation_run_time')
        batch_op.drop_index('ix_assimilation_field_time')

    op.drop_table('assimilation_states')
    # ### end Alembic commands ###
