"""add_observation_models

Revision ID: 98e23ab1a23e
Revises: 2f835ea301fc
Create Date: 2026-06-17 14:54:14.719261

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '98e23ab1a23e'
down_revision: Union[str, Sequence[str], None] = '2f835ea301fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('observation_batches',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('field_id', sa.Uuid(), nullable=True),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('provider_name', sa.String(length=128), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('number_of_observations', sa.Integer(), nullable=False),
    sa.Column('processing_status', sa.Enum('PENDING', 'SUCCESS', 'PARTIAL', 'FAILED', name='batch_processing_status_enum'), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('metadata_payload', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['field_id'], ['fields.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('observation_batches', schema=None) as batch_op:
        batch_op.create_index('ix_obsbatch_field_start', ['field_id', 'start_time'], unique=False)
        batch_op.create_index('ix_obsbatch_provider', ['provider_name'], unique=False)
        batch_op.create_index('ix_obsbatch_source', ['source'], unique=False)
        batch_op.create_index('ix_obsbatch_status', ['processing_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_observation_batches_field_id'), ['field_id'], unique=False)

    op.create_table('observations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('field_id', sa.Uuid(), nullable=True),
    sa.Column('simulation_run_id', sa.Uuid(), nullable=True),
    sa.Column('batch_id', sa.Uuid(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('variable_name', sa.String(length=64), nullable=False),
    sa.Column('units', sa.String(length=32), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('uncertainty', sa.Float(), nullable=False),
    sa.Column('source', sa.Enum('SATELLITE', 'SENSOR', 'WEATHER', 'MANUAL', 'MODEL', name='observation_source_enum'), nullable=False),
    sa.Column('provider_name', sa.String(length=128), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('quality_score', sa.Integer(), nullable=True),
    sa.Column('cloud_cover', sa.Float(), nullable=True),
    sa.Column('status', sa.Enum('VALID', 'MISSING', 'OUTLIER', 'REJECTED', name='observation_status_enum'), nullable=False),
    sa.Column('raw_payload', sa.JSON(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['observation_batches.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['field_id'], ['fields.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['simulation_run_id'], ['simulation_runs.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('observations', schema=None) as batch_op:
        batch_op.create_index('ix_obs_batch_id', ['batch_id'], unique=False)
        batch_op.create_index('ix_obs_field_timestamp', ['field_id', 'timestamp'], unique=False)
        batch_op.create_index('ix_obs_source', ['source'], unique=False)
        batch_op.create_index('ix_obs_status', ['status'], unique=False)
        batch_op.create_index('ix_obs_variable_timestamp', ['variable_name', 'timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_observations_batch_id'), ['batch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_observations_field_id'), ['field_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_observations_simulation_run_id'), ['simulation_run_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('observations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_observations_simulation_run_id'))
        batch_op.drop_index(batch_op.f('ix_observations_field_id'))
        batch_op.drop_index(batch_op.f('ix_observations_batch_id'))
        batch_op.drop_index('ix_obs_variable_timestamp')
        batch_op.drop_index('ix_obs_status')
        batch_op.drop_index('ix_obs_source')
        batch_op.drop_index('ix_obs_field_timestamp')
        batch_op.drop_index('ix_obs_batch_id')

    op.drop_table('observations')
    with op.batch_alter_table('observation_batches', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_observation_batches_field_id'))
        batch_op.drop_index('ix_obsbatch_status')
        batch_op.drop_index('ix_obsbatch_source')
        batch_op.drop_index('ix_obsbatch_provider')
        batch_op.drop_index('ix_obsbatch_field_start')

    op.drop_table('observation_batches')
    # ### end Alembic commands ###
