"""extend_daily_output_add_live_state_columns

Revision ID: 998b3739abb4
Revises: ca28c2635b9d
Create Date: 2026-06-12 13:32:24.194078

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '998b3739abb4'
down_revision: Union[str, Sequence[str], None] = 'ca28c2635b9d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('daily_outputs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('wlv', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('wst', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('wrt', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('wso', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('daily_outputs', schema=None) as batch_op:
        batch_op.drop_column('wso')
        batch_op.drop_column('wrt')
        batch_op.drop_column('wst')
        batch_op.drop_column('wlv')

    # ### end Alembic commands ###
