"""add_assimilation_run

Revision ID: f16eb05e3297
Revises: 29baced2da3c
Create Date: 2026-06-22 15:26:56.890320

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f16eb05e3297'
down_revision: Union[str, Sequence[str], None] = '29baced2da3c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'assimilation_runs',
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('simulation_id', sa.Uuid(), nullable=False),
        sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
        sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('status', sa.String(length=32), nullable=False),
        sa.Column('ensemble_size', sa.Integer(), nullable=False),
        sa.Column('total_cycles', sa.Integer(), nullable=False),
        sa.Column('executed_cycles', sa.Integer(), nullable=False),
        sa.Column('skipped_cycles', sa.Integer(), nullable=False),
        sa.Column('observations_used', sa.Integer(), nullable=False),
        sa.Column('config_json', sa.JSON(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
        sa.ForeignKeyConstraint(['simulation_id'], ['simulation_runs.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assimilation_runs_simulation_id'), 'assimilation_runs', ['simulation_id'], unique=False)

    with op.batch_alter_table('assimilation_states', schema=None) as batch_op:
        batch_op.add_column(sa.Column('assimilation_run_id', sa.Uuid(), nullable=True))
        batch_op.create_index('ix_assimilation_assim_run_time', ['assimilation_run_id', 'assimilation_time'], unique=False)
        batch_op.create_index(batch_op.f('ix_assimilation_states_assimilation_run_id'), ['assimilation_run_id'], unique=False)
        batch_op.create_foreign_key('fk_assimilation_states_assimilation_runs', 'assimilation_runs', ['assimilation_run_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assimilation_states', schema=None) as batch_op:
        batch_op.drop_constraint('fk_assimilation_states_assimilation_runs', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_assimilation_states_assimilation_run_id'))
        batch_op.drop_index('ix_assimilation_assim_run_time')
        batch_op.drop_column('assimilation_run_id')

    op.drop_index(op.f('ix_assimilation_runs_simulation_id'), table_name='assimilation_runs')
    op.drop_table('assimilation_runs')
    # ### end Alembic commands ###
