"""
scenario/models/scenario_definition.py — ScenarioDefinition ORM Model
=======================================================================

A ScenarioDefinition is the blueprint of a what-if analysis:

    "Starting from baseline simulation <base_simulation_id>, vary
     <parameter_name> across <parameter_values> using the
     <generator_type> generator."

Design rationale:
  - One ScenarioDefinition → many ScenarioRuns (one per candidate value).
  - The definition is immutable after creation — if you want to change
    the parameter grid, create a new definition.
  - parameter_values is stored as a JSON array because its element type
    differs per generator:
      SOWING_DATE → list of ISO date strings   ["2020-10-01", "2020-10-15", ...]
      IRRIGATION  → list of schedule dicts     [{"events": [...]}, ...]
      VARIETY     → list of variety strings    ["apache", "Winter_wheat_101", ...]

Relationship chain:
  ScenarioDefinition
      └── ScenarioRun (one per candidate value)
              └── SimulationRun (the actual WOFOST run, FK)

Table: scenario_definitions

NOT implemented here:
  - Execution service or generator logic
  - API routes
"""

import datetime
import enum
import uuid
from typing import Any, TYPE_CHECKING

from sqlalchemy import DateTime, Enum, ForeignKey, Index, JSON, String, Text
from sqlalchemy.orm import Mapped, mapped_column, relationship
from sqlalchemy.types import Uuid

from backend.app.db.base import Base, TimestampMixin

if TYPE_CHECKING:
    from backend.app.scenario.models.scenario_run import ScenarioRun


# ── Generator type vocabulary ─────────────────────────────────────────────────

class GeneratorType(str, enum.Enum):
    """Identifies which parameter dimension the scenario explores.

    The generator type tells the execution engine:
      1. Which request field to vary (e.g. sowing_date, irrigation_events, variety)
      2. How to interpret each element of parameter_values
      3. Which display label to use in comparison charts

    Values:
        SOWING_DATE — vary the crop sowing date across a calendar grid.
                      Each parameter_value is an ISO date string (YYYY-MM-DD).
                      Example: ["2020-10-01", "2020-10-15", "2020-11-01"]

        IRRIGATION  — vary the irrigation schedule applied to the crop.
                      Each parameter_value is a dict with an "events" key
                      whose value is a list of {date, amount_mm} dicts.
                      Example: [{"events": []}, {"events": [{"date":"...", "amount_mm":50}]}]

        VARIETY     — vary the crop variety, holding all other inputs constant.
                      Each parameter_value is a WOFOST variety string.
                      The crop name stays fixed (taken from the base simulation).
                      Example: ["apache", "Winter_wheat_101", "Hereward"]
    """
    SOWING_DATE = "SOWING_DATE"
    IRRIGATION  = "IRRIGATION"
    VARIETY     = "VARIETY"


# ── ORM Model ─────────────────────────────────────────────────────────────────

class ScenarioDefinition(TimestampMixin, Base):
    """Blueprint of a what-if scenario analysis.

    Records what parameter to vary, across what candidate values, and
    against which baseline simulation.  The execution service reads this
    record and spawns one ScenarioRun per candidate value.

    Table: scenario_definitions
    """

    __tablename__ = "scenario_definitions"

    __table_args__ = (
        # Fast lookup: "all scenarios built on a given baseline simulation"
        Index("ix_scendef_base_sim", "base_simulation_id"),
        # Common filter: "all SOWING_DATE scenarios"
        Index("ix_scendef_generator_type", "generator_type"),
    )

    # ── Primary key ───────────────────────────────────────────────────────
    id: Mapped[uuid.UUID] = mapped_column(
        Uuid(as_uuid=True),
        primary_key=True,
        default=uuid.uuid4,
        doc=(
            "UUID primary key.  Generated by the application at creation time "
            "so the caller can reference the scenario before any runs are stored."
        ),
    )

    # ── Human-readable identity ───────────────────────────────────────────
    name: Mapped[str] = mapped_column(
        String(256),
        nullable=False,
        doc=(
            "Short, descriptive name for this scenario. "
            "Shown in comparison tables and API list responses. "
            "Example: 'Sowing date sweep — Delhi wheat 2020'."
        ),
    )

    description: Mapped[str | None] = mapped_column(
        Text,
        nullable=True,
        doc=(
            "Optional longer explanation of the scenario purpose, hypotheses, "
            "and expected outcomes.  Free text — no format enforced. "
            "Shown in detailed scenario view and exported reports."
        ),
    )

    # ── Parameter configuration ───────────────────────────────────────────
    generator_type: Mapped[GeneratorType] = mapped_column(
        Enum(GeneratorType, name="generator_type_enum"),
        nullable=False,
        doc=(
            "Which parameter dimension this scenario explores. "
            "One of: SOWING_DATE, IRRIGATION, VARIETY. "
            "Tells the execution service how to interpret parameter_values "
            "and which SimulateRequest field to override per run. "
            "See GeneratorType docstring for per-value formats."
        ),
    )

    parameter_name: Mapped[str] = mapped_column(
        String(128),
        nullable=False,
        doc=(
            "Name of the SimulateRequest field that is varied across runs. "
            "Must be a valid JSON path in the SimulateRequest schema. "
            "Canonical values per generator_type: "
            "  SOWING_DATE → 'sowing_date' "
            "  IRRIGATION  → 'irrigation_events' "
            "  VARIETY     → 'variety' "
            "Stored explicitly (not derived from generator_type) so that "
            "future generator types can target any request field without "
            "changing the schema (e.g. 'harvest_date', 'max_duration')."
        ),
    )

    parameter_values: Mapped[list[Any]] = mapped_column(
        JSON,
        nullable=False,
        doc=(
            "JSON array of candidate values to test for parameter_name. "
            "Each element becomes one ScenarioRun. "
            "Element format depends on generator_type: "
            "  SOWING_DATE → ISO date strings: ['2020-10-01', '2020-10-15', ...] "
            "  IRRIGATION  → schedule dicts: [{'events': [{date, amount_mm}, ...]}, ...] "
            "  VARIETY     → variety name strings: ['apache', 'Winter_wheat_101', ...] "
            "Minimum 2 values required (a single value is just a baseline rerun). "
            "Maximum 50 values recommended to keep runtime manageable."
        ),
    )

    # ── Anchor to baseline simulation ─────────────────────────────────────
    base_simulation_id: Mapped[uuid.UUID | None] = mapped_column(
        Uuid(as_uuid=True),
        ForeignKey("simulation_runs.id", ondelete="SET NULL"),
        nullable=True,
        index=True,
        doc=(
            "FK → simulation_runs.id — the 'control' simulation against which "
            "all scenario runs are compared. "
            "The baseline run provides: crop, variety, location, weather/soil flags, "
            "and all fixed parameters that are NOT being varied. "
            "NULL is allowed so that a ScenarioDefinition can be created before "
            "the baseline simulation exists (e.g. draft scenarios). "
            "SET NULL on delete preserves the scenario definition if the baseline "
            "run is deleted — the scenario's own runs remain valid for comparison."
        ),
    )

    # ── Relationships ──────────────────────────────────────────────────────
    runs: Mapped[list["ScenarioRun"]] = relationship(
        "ScenarioRun",
        back_populates="scenario",
        cascade="all, delete-orphan",
        order_by="ScenarioRun.created_at",
        doc=(
            "Ordered list of ScenarioRun records, one per candidate value. "
            "Populated by the scenario execution service after this definition "
            "is submitted for execution. "
            "CASCADE: deleting a ScenarioDefinition deletes all its runs."
        ),
    )

    def __repr__(self) -> str:
        return (
            f"<ScenarioDefinition id={self.id!s:.8} "
            f"name={self.name!r} "
            f"generator={self.generator_type.value} "
            f"n_values={len(self.parameter_values) if self.parameter_values else 0}>"
        )
